### ISSUE TITLE
Use VS Code built-in `Developer: Generate Color Theme From Current Settings`

### ISSUE THREAD

**Issue by 2zqa** [kcamcam/vscode_dark_modern.zed#6]
Today I discovered the `Developer: Generate Color Theme From Current Settings` VS Code command, that generates an exhaustive file with all theme settings applied. This ensures that the theme_importer program has no errors for missing data. They can be used as a base.

I've provided two files below from a stock VS Code installation.

* [modern-dark.json](https://github.com/user-attachments/files/16317747/modern-dark.json)
* [modern-light.json](https://github.com/user-attachments/files/16317748/modern-light.json)

**Comment by 2zqa** [comment]
I wanted to use this as a new base for this repository myself, but I noticed it would overwrite some values that were already provided. I suppose those were edited manually and should be kept as-is?

To keep the diffs nice, I made all hex values uppercase. (I needed VS Code for this still sadly)

| search    | replace   |
|-----------|-----------|
| `"#(.*)"` | `"#\U$1"` |

I recommend you to check it out to see which values should or should not be used.

**Comment by kcamcam** [comment]
Thanks for sharing the find @2zqa. 

I think it would be safe to assume that the values supplied by the theme generator are correct and should be used instead of the values we currently have. 

Please open a pull request if/when you can it would be most welcome. I look forward to filling in some of the blank values that are missing.

Let me know how I can help. Since I think this might end up changing quite a few values please free to omit any before and after screen shots to save time. I will manually inspect them during review.

**Comment by kcamcam** [comment]
> I wanted to use this as a new base for this repository myself, but I noticed it would overwrite some values that were already provided. I suppose those were edited manually and should be kept as-is?
> 
> To keep the diffs nice, I made all hex values uppercase. (I needed VS Code for this still sadly)
> search 	replace
> `"#(.*)"` 	`"#\U$1"`
> 
> I recommend you to check it out to see which values should or should not be used.

I come back to VS Code frequently for features that Zed is still missing, like Markdown rendering of Mermaid diagram code blocks. I am happy to revisit VS Code as I still love the editor. But I do look forward to seeing Zed's progress and start filling in a lot of the missing features, at what seems like a quick pace.
